# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1XR5CM3dXyY1UNWQzthaen945Xhw8Qj
"""

import pandas as pd
baza={
     "Fish": [ "Aliyev Ali" , "Aliyeva Ra'no", "Aliyev Yusuf", "G'aniyev Bosit", "Xolmatov MUrodill","Aliyev Fozil", "Abdurahmonov Donyor", "Abdullayev Shahriyor","Usmonov Yusuf","Pozilov Abdulaziz"],
     "Yoshi":[  '11'  , "16" ,"17","18","19","18","19", "19","19","18" ],
     "Maktabi": ['6-maktab'  ,"Prezident maktabi" ,'7-maktab', "16-maktab", '15-maktab', '28-maktab','1-maktab','24-maktab','29-maktab','33-maktab'],
     "Jinsi": [ 'erkak' , 'ayol','erkak', 'erkak','erkak','erkak','erkak','erkak','erkak','erkak'],
     "Manzil":["Farg'ona shaxar","Andijon shahar","Namangan shahar","Farg'ona shaxar","Namangan shahar","Andijon shahar","Andijon shahar","Farg'ona shaxar","Andijon shahar", "Farg'ona shaxar"]
 }
malumot=pd.DataFrame(baza)
print(malumot)

filtr = malumot[(malumot['Jinsi'] == "erkak" ) & (malumot["Manzil"] == "Farg'ona shaxar") & (malumot["Yoshi"] > "16") ]
print (filtr)